import Header from "@/components/header";
import "@/styles/layout.scss"
import "@/styles/components.scss"
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body>
        <Header />
        <div id="content">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
